# Generated by Django 4.2.1 on 2023-05-11 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JezioroPlotki', '0002_temperature_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
