# Generated by Django 4.2.1 on 2023-05-11 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JezioroPlotki', '0003_temperature_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='date',
            new_name='edit_date',
        ),
    ]
